modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="nickname"
version="${file.jarVersion}"
displayName="Nickname"

# We will come back later.
credits=""

authors="3TUSK"

description="A mod that adds a /nick command, simple as that."

[[dependencies.nickname]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15, 1.15.2]"
    ordering="NONE"
    side="BOTH"