modLoader="javafml"
loaderVersion="[28,)"

license="BSD 3-Clause"

[[mods]]
modId="nickname"
version="${file.jarVersion}"
displayName="Nickname"

# We will come back later.
credits=""

authors="3TUSK"

description="A mod that adds a /nick command, simple as that."
